package analyzer

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
)

func TestDeviceRulePackReportsDocumentedProfileViolations(t *testing.T) {
	snapshot, err := LoadPackages(context.Background(), LoadConfig{ModuleRoot: contractFixtureRoot(), Patterns: []string{"./noncompliant"}, Target: TargetDevice})
	if err != nil {
		t.Fatal(err)
	}
	if snapshotHasLoadErrors(snapshot) {
		t.Fatalf("fixture load errors: %+v", snapshot.Packages)
	}
	catalog, err := NewRuleCatalog(ContractInventory())
	if err != nil {
		t.Fatal(err)
	}
	registry, err := NewRegistry(catalog, deviceRuleRegistrations()...)
	if err != nil {
		t.Fatal(err)
	}
	result, err := registry.Run(context.Background(), snapshot, RuleSelection{Families: []RuleFamily{FamilyDevice}})
	if err != nil {
		t.Fatal(err)
	}
	seen := make(map[RuleID]bool)
	for _, finding := range result.Findings {
		seen[finding.RuleID] = true
	}
	var got []RuleID
	for rule := range seen {
		got = append(got, rule)
	}
	sort.Slice(got, func(i, j int) bool { return got[i] < got[j] })
	want := []RuleID{"device-channel", "device-encoding-json", "device-finalizer", "device-fmt", "device-goroutine", "device-recover", "device-reflect-symbol", "device-runtime-control", "device-select", "device-time-runtime"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("reported rules = %v, want %v", got, want)
	}
}

func TestDeviceRulePackAcceptsDocumentedSubsetAndOtherTargets(t *testing.T) {
	options, err := DefaultCheckOptions()
	if err != nil {
		t.Fatal(err)
	}
	for _, test := range []struct {
		name    string
		pattern string
		target  Target
	}{
		{name: "documented device subset", pattern: "./compliant", target: TargetDevice},
		{name: "noncompliant code is valid for simulator", pattern: "./noncompliant", target: TargetSimulator},
	} {
		t.Run(test.name, func(t *testing.T) {
			snapshot, err := LoadPackages(context.Background(), LoadConfig{ModuleRoot: contractFixtureRoot(), Patterns: []string{test.pattern}, Target: test.target})
			if err != nil {
				t.Fatal(err)
			}
			result, err := options.Registry.Run(context.Background(), snapshot, RuleSelection{Families: []RuleFamily{FamilyDevice}})
			if err != nil {
				t.Fatal(err)
			}
			if len(result.Findings) != 0 {
				t.Fatalf("findings = %+v, want none", result.Findings)
			}
		})
	}
}

func TestDeviceCgoRulePrecedesToolchainLoadFailure(t *testing.T) {
	options, err := DefaultCheckOptions()
	if err != nil {
		t.Fatal(err)
	}
	snapshot, err := LoadPackages(context.Background(), LoadConfig{
		ModuleRoot: contractFixtureRoot(), Patterns: []string{"./noncompliant"}, BuildTags: []string{"analyzer_cgo"}, Target: TargetDevice,
	})
	if err != nil {
		t.Fatal(err)
	}
	if snapshotHasLoadErrors(snapshot) {
		t.Fatalf("device cgo preflight left load errors: %+v", snapshot.Packages)
	}
	result, err := options.Registry.Run(context.Background(), snapshot, RuleSelection{IDs: []RuleID{"device-cgo"}})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Findings) != 1 || result.Findings[0].RuleID != "device-cgo" || !strings.HasSuffix(result.Findings[0].Position, "noncompliant/cgo.go:6:8") {
		t.Fatalf("cgo findings = %+v", result.Findings)
	}
}

func TestDefaultCheckOptionsRegistersEveryInitialDeviceRule(t *testing.T) {
	options, err := DefaultCheckOptions()
	if err != nil {
		t.Fatal(err)
	}
	rules, err := options.Catalog.Select(RuleSelection{Families: []RuleFamily{FamilyDevice}})
	if err != nil {
		t.Fatal(err)
	}
	for _, rule := range rules {
		if rule.Family == FamilyDevice && options.Registry.registrations[rule.ID] == nil {
			t.Errorf("device rule %q is not registered", rule.ID)
		}
	}
}

func TestDeviceRulesReportForbiddenSymbolReferencesAndChannelRange(t *testing.T) {
	root := checkFixture(t, `package game
import (
	"reflect"
	"runtime"
	"time"
)
var _ = time.Now
var _ *time.Timer
var _ = reflect.MakeFunc
var _ = runtime.LockOSThread
func drain(channel <-chan int) { for range channel {} }
`)
	options, err := DefaultCheckOptions()
	if err != nil {
		t.Fatal(err)
	}
	snapshot, err := LoadPackages(context.Background(), LoadConfig{ModuleRoot: root, Target: TargetDevice})
	if err != nil {
		t.Fatal(err)
	}
	result, err := options.Registry.Run(context.Background(), snapshot, RuleSelection{IDs: []RuleID{"device-channel", "device-reflect-symbol", "device-runtime-control", "device-time-runtime"}})
	if err != nil {
		t.Fatal(err)
	}
	seen := make(map[RuleID]int)
	for _, finding := range result.Findings {
		seen[finding.RuleID]++
	}
	if seen["device-time-runtime"] != 2 || seen["device-reflect-symbol"] != 1 || seen["device-runtime-control"] != 1 || seen["device-channel"] != 2 {
		t.Fatalf("finding counts = %v", seen)
	}
}

func TestDeviceRuleCommandSourcePolicies(t *testing.T) {
	options, err := DefaultCheckOptions()
	if err != nil {
		t.Fatal(err)
	}
	root := checkFixture(t, "package game\n")
	options.ModuleRoot = root
	writeAnalyzerFixture(t, root, "generated.go", "// Code generated by analyzer fixture. DO NOT EDIT.\n\npackage game\nfunc generated() { go func() {}() }\n")
	writeAnalyzerFixture(t, root, "tagged.go", "//go:build analyzer_extra\n\npackage game\nfunc tagged() { go func() {}() }\n")
	writeAnalyzerFixture(t, root, "game_test.go", "package game\nfunc testOnly() { go func() {}() }\n")

	assertDeviceCheck(t, options, []string{"check", "--target", "device", "--rules", "device-goroutine"}, ExitSuccess, "No findings.")
	assertDeviceCheck(t, options, []string{"check", "--target", "device", "--rules", "device-goroutine", "--generated", "include"}, ExitFindings, "generated.go")
	assertDeviceCheck(t, options, []string{"check", "--target", "device", "--rules", "device-goroutine", "--tags", "analyzer_extra"}, ExitFindings, "tagged.go")
	assertDeviceCheck(t, options, []string{"check", "--target", "device", "--rules", "device-goroutine", "--tests"}, ExitFindings, "game_test.go")
}

func TestDeviceRuleCommandSuppressionAndBothTargets(t *testing.T) {
	options, err := DefaultCheckOptions()
	if err != nil {
		t.Fatal(err)
	}
	options.ModuleRoot = checkFixture(t, "package game\nfunc bad() {\n//gopdsdk:ignore device-goroutine -- fixture exception\ngo func() {}()\n}\n")
	assertDeviceCheck(t, options, []string{"check", "--target", "both", "--rules", "device-goroutine"}, ExitSuccess, "suppressed inline: fixture exception")
}

func assertDeviceCheck(t *testing.T, options CheckOptions, arguments []string, wantCode int, contains string) {
	t.Helper()
	var stdout, stderr bytes.Buffer
	err := RunCheck(context.Background(), arguments, &stdout, &stderr, options)
	if wantCode == ExitSuccess {
		if err != nil {
			t.Fatalf("RunCheck(%v) = %v", arguments, err)
		}
	} else {
		var commandError *CommandError
		if !errors.As(err, &commandError) || commandError.Code != wantCode {
			t.Fatalf("RunCheck(%v) = %v, want exit %d", arguments, err, wantCode)
		}
	}
	if !strings.Contains(stdout.String(), contains) {
		t.Fatalf("RunCheck(%v) output missing %q:\n%s\nstderr: %s", arguments, contains, stdout.String(), stderr.String())
	}
}

func writeAnalyzerFixture(t *testing.T, root, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, name), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
