package analyzer

// ContractInventory returns the initial static contract catalog. Returned
// slices are independent and may be sorted or filtered by callers.
func ContractInventory() Inventory {
	return Inventory{
		Schema: "gopdsdk-analyzer-contracts/v1",
		Contracts: []Contract{
			{ID: "device-scheduler-replacement", Kind: ContractReplacement, Subject: "goroutines, channels, select, sleep, timers, and tickers", Targets: []Target{TargetDevice}, NormativeRef: "API.md#bounded-cooperative-scheduling", Statement: "device games use playdate/schedule for bounded cooperative work", PositiveCase: "a device package advances a schedule.Scheduler from Game.Update", NegativeCase: "a device package starts a goroutine or creates a channel"},
			{ID: "device-json-replacement", Kind: ContractReplacement, Subject: "encoding/json", Targets: []Target{TargetDevice}, NormativeRef: "API.md#bounded-json", Statement: "device games use playdate/json for bounded reflection-free JSON", PositiveCase: "a device package decodes with playdate/json", NegativeCase: "a device package imports encoding/json"},
			{ID: "context-optional-capability", Kind: ContractOptionalCapability, Subject: "playdate.Context optional interfaces", Targets: []Target{TargetShared}, NormativeRef: "API.md#context-capabilities", Statement: "capabilities outside Context's five embedded interfaces require a checked assertion", PositiveCase: "a game uses comma-ok before calling Launcher.ExitToLauncher", NegativeCase: "a game uses a single-value assertion to playdate.Launcher"},
			{ID: "framebuffer-callback-scope", Kind: ContractCallbackScope, Subject: "playdate.Framebuffer", Targets: []Target{TargetShared}, NormativeRef: "API.md#context-capabilities", Statement: "a framebuffer view and its bytes do not outlive WithFramebuffer", PositiveCase: "a callback copies required framebuffer bytes", NegativeCase: "a callback stores Framebuffer.Bytes in a package variable"},
			{ID: "bitmap-owned-handle", Kind: ContractOwnedHandle, Subject: "playdate.Bitmap", Targets: []Target{TargetShared}, NormativeRef: "API.md#bitmap-ownership-and-errors", Statement: "LoadBitmap and NewBitmap return handles closed exactly once by their owner", PositiveCase: "a successfully loaded bitmap is closed during termination", NegativeCase: "a successfully loaded bitmap is lost without Close"},
			{ID: "bitmap-table-borrowed-frame", Kind: ContractBorrowedHandle, Subject: "playdate.BitmapTable.Frame", Targets: []Target{TargetShared}, NormativeRef: "API.md#bitmap-ownership-and-errors", Statement: "bitmap table frames are borrowed from the table and are not closed", PositiveCase: "a frame remains in use only while its table is live", NegativeCase: "a caller closes a bitmap returned by BitmapTable.Frame"},
			{ID: "menu-image-retention", Kind: ContractRetention, Subject: "playdate.SystemControls.SetMenuImage", Targets: []Target{TargetShared}, NormativeRef: "API.md#context-capabilities", Statement: "the runtime retains the menu bitmap until clear, replacement, or termination", PositiveCase: "ClearMenuImage precedes closing the installed bitmap", NegativeCase: "the installed bitmap is closed while retained as the menu image"},
			{ID: "bitmap-close-semantics", Kind: ContractClose, Subject: "playdate.Bitmap.Close", Targets: []Target{TargetShared}, NormativeRef: "API.md#bitmap-ownership-and-errors", Statement: "an owned bitmap is closed exactly once and is not used afterward", PositiveCase: "the owner closes a live unretained bitmap once", NegativeCase: "the owner draws a bitmap after a successful Close"},
			{ID: "scheduler-update-boundary", Kind: ContractUpdateOnly, Subject: "playdate/schedule.Scheduler.Update", Targets: []Target{TargetShared}, NormativeRef: "API.md#bounded-cooperative-scheduling", Statement: "Scheduler.Update is called only from the application update boundary", PositiveCase: "Game.Update calls Scheduler.Update", NegativeCase: "an initialization helper calls Scheduler.Update"},
			{ID: "menu-image-offset-bound", Kind: ContractArgumentBound, Subject: "playdate.SystemControls.SetMenuImage xOffset", Targets: []Target{TargetShared}, NormativeRef: "API.md#context-capabilities", Statement: "menu image xOffset is between 0 and 200 inclusive", PositiveCase: "SetMenuImage receives an xOffset of 200", NegativeCase: "SetMenuImage receives an xOffset of 201"},
			{ID: "video-capability-availability", Kind: ContractAvailability, Subject: "playdate.Videos", Targets: []Target{TargetSimulator, TargetDevice}, NormativeRef: "API.md#context-capabilities", Statement: "video is an optional capability and LoadVideo is the supported packaged PDV surface", PositiveCase: "a checked Videos capability loads a packaged PDV", NegativeCase: "a game assumes every Context implements Videos"},
		},
		Rules: []Rule{
			{ID: "device-goroutine", Family: FamilyDevice, Summary: "goroutines are unavailable in the device profile", Default: SeverityError, Confidence: ConfidenceProven, Targets: []Target{TargetDevice}, ContractIDs: []string{"device-scheduler-replacement"}, Suppressible: true, SafeFixPolicy: "none; scheduling semantics require a manual rewrite"},
			{ID: "device-encoding-json", Family: FamilyDevice, Summary: "encoding/json is unavailable in the device profile", Default: SeverityError, Confidence: ConfidenceProven, Targets: []Target{TargetDevice}, ContractIDs: []string{"device-json-replacement"}, Suppressible: true, SafeFixPolicy: "none; schemas require a manual bounded decoder"},
			{ID: "capability-unchecked-assertion", Family: FamilyCapability, Summary: "an optional Context capability is asserted without a check", Default: SeverityError, Confidence: ConfidenceProven, Targets: []Target{TargetShared}, ContractIDs: []string{"context-optional-capability"}, Suppressible: true, SafeFixPolicy: "introduce comma-ok only when control flow remains explicit"},
			{ID: "lifetime-framebuffer-escape", Family: FamilyLifetime, Summary: "callback-scoped framebuffer data escapes its callback", Default: SeverityError, Confidence: ConfidenceProven, Targets: []Target{TargetShared}, ContractIDs: []string{"framebuffer-callback-scope"}, Suppressible: true, SafeFixPolicy: "none; the required ownership and copy policy is application-specific"},
			{ID: "ownership-bitmap-use-after-close", Family: FamilyOwnership, Summary: "an owned bitmap is used after successful close", Default: SeverityError, Confidence: ConfidenceProven, Targets: []Target{TargetShared}, ContractIDs: []string{"bitmap-owned-handle", "bitmap-close-semantics"}, Suppressible: true, SafeFixPolicy: "none; lifetime restructuring is application-specific"},
			{ID: "application-scheduler-update-boundary", Family: FamilyApplication, Summary: "scheduler update runs outside Game.Update", Default: SeverityError, Confidence: ConfidenceProven, Targets: []Target{TargetShared}, ContractIDs: []string{"scheduler-update-boundary"}, Suppressible: true, SafeFixPolicy: "none; moving work can change application behavior"},
			{ID: "result-menu-image-offset", Family: FamilyResult, Summary: "menu image offset is outside the accepted range", Default: SeverityError, Confidence: ConfidenceProven, Targets: []Target{TargetShared}, ContractIDs: []string{"menu-image-offset-bound"}, Suppressible: true, SafeFixPolicy: "replace only a constant value when intent is unambiguous"},
			{ID: "performance-frame-allocation", Family: FamilyPerformance, Summary: "a statically visible allocation is reachable from a frame callback", Default: SeverityPerformance, Confidence: ConfidenceHeuristic, Targets: []Target{TargetShared}, ContractIDs: []string{"scheduler-update-boundary"}, Experimental: true, Suppressible: true, SafeFixPolicy: "none; runtime measurement and application design are required"},
		},
		RuntimeMeasurements: []string{
			"exact allocation counts and heap or stack bounds",
			"frame time, audio underruns, and power consumption",
			"native handle state and callback delivery",
			"SDK conversion, Simulator loading, USB, and physical-device behavior",
		},
	}
}
