package analyzer

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"

	"golang.org/x/tools/go/packages"
)

// go list with cgo disabled omits cgo-only directories from ./... entirely.
// Metadata discovery with cgo enabled needs no C compiler. A virtual package
// clause then keeps those selected packages visible to the ordinary loader;
// their actual C imports are restored by includeIgnoredCgoSources.
func includeCgoOnlyPackages(config *packages.Config, patterns []string) (map[string]bool, error) {
	discovery := *config
	discovery.Mode = packages.NeedName | packages.NeedFiles
	discovery.Env = environmentWith("CGO_ENABLED", "1")
	discovery.Tests = false
	listed, err := packages.Load(&discovery, patterns...)
	if err != nil {
		return nil, fmt.Errorf("discover cgo packages: %w", err)
	}
	stubs := make(map[string]bool)
	for _, pkg := range listed {
		if err := config.Context.Err(); err != nil {
			return nil, err
		}
		if pkg.Name == "" || len(pkg.GoFiles) == 0 || len(pkg.Errors) != 0 {
			continue
		}
		onlyCgo := true
		for _, name := range pkg.GoFiles {
			data := config.Overlay[filepath.Clean(name)]
			if data == nil {
				data, err = os.ReadFile(name)
				if err != nil {
					return nil, err
				}
			}
			file, parseErr := parser.ParseFile(token.NewFileSet(), name, data, parser.ImportsOnly)
			if parseErr != nil || !astFileImports(file, "C") {
				onlyCgo = false
				break
			}
		}
		if !onlyCgo {
			continue
		}
		for index := 0; ; index++ {
			name := filepath.Join(filepath.Dir(pkg.GoFiles[0]), fmt.Sprintf("zz_gopdsdk_check_cgo_%d.go", index))
			if _, exists := config.Overlay[name]; exists {
				continue
			}
			if _, err := os.Stat(name); err == nil {
				continue
			} else if !os.IsNotExist(err) {
				return nil, err
			}
			if config.Overlay == nil {
				config.Overlay = make(map[string][]byte)
			}
			config.Overlay[name] = []byte("// Code generated by gopdsdk check. DO NOT EDIT.\n\npackage " + pkg.Name + "\n")
			stubs[name] = true
			break
		}
	}
	return stubs, nil
}

func removeCgoStubSources(pkg *packages.Package, stubs map[string]bool) {
	if len(stubs) == 0 {
		return
	}
	pkg.GoFiles = slices.DeleteFunc(pkg.GoFiles, func(name string) bool { return stubs[filepath.Clean(name)] })
	pkg.CompiledGoFiles = slices.DeleteFunc(pkg.CompiledGoFiles, func(name string) bool { return stubs[filepath.Clean(name)] })
	pkg.Syntax = slices.DeleteFunc(pkg.Syntax, func(file *ast.File) bool { return stubs[filepath.Clean(pkg.Fset.Position(file.Pos()).Filename)] })
}
